# Generated by Django 2.1.5 on 2019-06-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=500)),
                ('treatment', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('bpi', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='consult',
            name='consult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
    ]
